#!/bin/sh

_PYTHON="/usr/bin/python"
_CACHE="/pkg"
_XML="/usr/share/cnchi/data/packages.xml"
_OPTIONS="-dvz"

if [ -f /usr/bin/python3 ]; then
    _PYTHON="/usr/bin/python3"
fi

sudo -E $_PYTHON cnchi.py $_OPTIONS -c $_CACHE -p $_XML $1 $2 $3 $4




