#!/bin/bash

# WARNING:
# This script is a helper that the developers use to call Cnchi (testing purposes only)
# Please, do not use if your intention is to do a "normal" installation

CNCHI_DIR=`pwd`
sudo ln -sf $CNCHI_DIR /usr/share/cnchi

_PYTHON="/usr/bin/python"
_PYTHON_OPTIONS="-Wall"
_XML="/usr/share/cnchi/data/packages.xml"
_CNCHI_OPTIONS="-d -v --disable-rank-mirrors -s bugsnag"
_CNCHI_BIN="/usr/share/cnchi/bin/cnchi"

# Run Cnchi
pkexec $_CNCHI_BIN $_CNCHI_OPTIONS -p $_XML

exit 0

