#!/bin/bash

DESKTOP=$1

# Change keyboard layaout
dbus-launch gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"

# Set gtk theme
dbus-launch gsettings set org.gnome.desktop.interface gtk-theme Zukitwo
dbus-launch gsettings set org.gnome.desktop.wm.preferences theme Zukitwo

if [[ ${DESKTOP} == 'gnome' ]];then

	# Set favorite apps
	dbus-launch gsettings set org.gnome.shell favorite-apps "['nautilus.desktop', 'chromium.desktop', 'empathy.desktop', 'xnoise.desktop']"

	# Change default wallpaper
	dbus-launch gsettings set org.gnome.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png

fi

if [[ ${DESKTOP} == 'cinnamon' ]];then

	# Set menu icon
	dbus-launch gsettings set org.cinnamon menu-icon "/usr/share/antergos/antergos-menu.png"

	# Set favorite apps
	dbus-launch gsettings set org.cinnamon favorite-apps "['nemo.desktop', 'chromium.desktop', 'xnoise.desktop']"

	# Set overview corner to false
	dbus-launch gsettings set org.cinnamon overview-corner "['false:false:false', 'false:false:false', 'false:false:false', 'false:false:false']"

	# Set panel launchers
	dbus-launch gsettings set org.cinnamon panel-launchers "['chromium.desktop', 'nemo.desktop', 'gnome-terminal.desktop']"

	# Set panel orientation
	dbus-launch gsettings set org.cinnamon desktop-layout "flipped"

	# Set enabled applets
	dbus-launch gsettings set org.cinnamon enabled-applets "['panel1:left:1:menu@cinnamon.org:0', 'panel1:left:2:panel-launchers@cinnamon.org:1', 'panel1:left:3:window-list@cinnamon.org:2', 'panel1:right:0:removable-drives@cinnamon.org:3', 'panel1:right:1:keyboard@cinnamon.org:4', 'panel1:right:2:bluetooth@cinnamon.org:5', 'panel1:right:4:systray@cinnamon.org:7', 'panel1:right:5:power@cinnamon.org:8', 'panel1:right:6:network@cinnamon.org:6', 'panel1:right:7:sound@cinnamon.org:9', 'panel1:right:8:calendar@cinnamon.org:10', 'panel1:right:9:settings@cinnamon.org:11']"

	# Disable keyboard flags
	dbus-launch gsettings set org.cinnamon keyboard-applet-use-flags "false"
	
	# Set background
	dbus-launch gsettings set org.cinnamon.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png
	dbus-launch gsettings set org.gnome.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png

fi