#!/bin/bash
# -*- coding: utf-8 -*-
#
#  set-settings
#
#  Copyright © 2013-2016 Antergos
#
#  This file is part of Cnchi.
#
#  Cnchi is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Cnchi is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Cnchi; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.

# GNOME, CINNAMON, XFCE and MATE setups

CN_DESKTOP=$1

export DISPLAY=:0

# Start DBUS daemon if its not running
if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	eval `dbus-launch --sh-syntax`
	echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi

# Set default directories
xdg-user-dirs-update

terminal-profile() {
	_term=$1
	_schema="org.${_term}.Terminal.Legacy.Profile:/org/${_term}/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/"
	gsettings set "org.${_term}.Terminal.ProfilesList" default 'b1dcc9dd-5262-4d8d-a863-c897e6d979b9'
	gsettings set "org.${_term}.Terminal.ProfilesList" list "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']"
	gsettings set "${_schema}" use-theme-colors false
	gsettings set "${_schema}" background-color '#262626262626'
	gsettings set "${_schema}" foreground-color '#F8F8F8F8F2F2'
	gsettings set "${_schema}" visible-name 'antergos'
	gsettings set "${_schema}" palette "['#1B1B1D1D1E1E', '#F9F926267272', '#8282B4B41414', '#FDFD97971F1F', '#5656C2C2D6D6', '#8C8C5454FEFE', '#464654545757', '#CCCCCCCCC6C6', '#505053535454', '#FFFF59599595', '#B6B6E3E35454', '#FEFEEDED6C6C', '#8C8CEDEDFFFF', '#9E9E6F6FFEFE', '#89899C9CA1A1', '#F8F8F8F8F2F2']"
}

gnome() {

	# Change keyboard layout
	# The value of this setting is applied with sed from postinstall.sh before running set-settings.
	gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"

	# Set favorite apps
	gsettings set org.gnome.shell favorite-apps "['nautilus.desktop', 'gnome-terminal.desktop', \"${_BROWSER}.desktop\", 'pidgin.desktop', 'gnome-music.desktop']"

	gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'status-menu-buttons@dev.antergos.com', 'dash-to-dock@micxgx.gmail.com']"
	# Change default wallpaper
	gsettings set org.gnome.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png

	# Set GTK Theme
	gsettings set org.gnome.desktop.interface gtk-theme "Numix-Frost-Light"
	gsettings set org.gnome.desktop.wm.preferences theme "Numix-Frost-Light"
	gsettings set org.gnome.shell.extensions.user-theme name "Numix-Frost-Light"

	# Set icon theme
	gsettings set org.gnome.desktop.interface icon-theme "Numix-Square"

	# Min/Max Buttons
	gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

	gsettings set org.gnome.desktop.screensaver lock-enabled false
	gsettings set org.gnome.desktop.session idle-delay 0

	# Configure touchpad
	gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
	gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
	gsettings set org.gnome.desktop.peripherals.touchpad scroll-method 'two-finger-scrolling'

	terminal-profile 'gnome'
}

cinnamon() {

	# Change keyboard layout
	# The value of this setting is applied with sed from postinstall.sh before running set-settings.
	gsettings set org.cinnamon.desktop.input-sources sources "[('xkb','us')]"

	# Set gtk theme
	gsettings set org.cinnamon.desktop.interface gtk-theme "Numix-Frost-Light"
	gsettings set org.cinnamon.desktop.wm.preferences theme "Numix-Frost-Light"

	# Set favorite apps
	gsettings set org.cinnamon favorite-apps "['nemo.desktop', \"${_BROWSER}.desktop\", 'pamac.desktop', 'gnome-terminal.desktop']"

	# Set overview corner to false
	gsettings set org.cinnamon overview-corner "['false:false:false', 'false:false:false', 'false:false:false', 'false:false:false']"

	# Set panel orientation
	gsettings set org.cinnamon panels-enabled "['1:0:bottom']"

	# Set enabled applets
	gsettings set org.cinnamon enabled-applets "['panel1:left:1:menu@cinnamon.org:0', 'panel1:left:2:panel-launchers@cinnamon.org:1', 'panel1:left:3:window-list@cinnamon.org:2', 'panel1:right:0:removable-drives@cinnamon.org:3', 'panel1:right:1:keyboard@cinnamon.org:4', 'panel1:right:2:bluetooth@cinnamon.org:5', 'panel1:right:4:systray@cinnamon.org:7', 'panel1:right:5:power@cinnamon.org:8', 'panel1:right:6:network@cinnamon.org:6', 'panel1:right:7:sound@cinnamon.org:9', 'panel1:right:8:calendar@cinnamon.org:10', 'panel1:right:9:settings@cinnamon.org:11']"
	# Accordingly set next-applet-id
	gsettings set org.cinnamon next-applet-id 12

	# Disable keyboard flags
	gsettings set org.cinnamon keyboard-applet-use-flags "false"

	# Set background
	gsettings set org.cinnamon.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png
	gsettings set org.gnome.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png

	# Set theme
	gsettings set org.cinnamon.theme name "Numix-Frost"

	# Set icon theme
	gsettings set org.cinnamon.desktop.interface icon-theme "Numix-Square"
	gsettings set org.gnome.desktop.interface icon-theme "Numix-Square"

	# Configure touchpad
	gsettings set org.cinnamon.settings-daemon.peripherals.touchpad tap-to-click true
	gsettings set org.cinnamon.settings-daemon.peripherals.touchpad touchpad-enabled true
	gsettings set org.cinnamon.settings-daemon.peripherals.touchpad scroll-method 'two-finger-scrolling'

	terminal-profile 'gnome'

}

xfce() {

	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml

	# Set background for workspaces 0 and 1
	xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -n -t string -s "/usr/share/antergos/wallpapers/antergos-wallpaper.png"
	CMD=`grep last-image ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep last-image ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done
	xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace1/last-image -n -t string -s "/usr/share/antergos/wallpapers/antergos-wallpaper.png"
	CMD=`grep last-image ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep last-image ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done

	# Set theme
	xfconf-query -c xsettings -p /Net/ThemeName -n -t string -s "Numix-Frost"
	CMD=`grep ThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep ThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done

	xfconf-query -c xfwm4 -p /general/theme -n -t string -s "Numix-Frost-Light"
	CMD=`grep theme ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep theme ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done

	# Set icon theme
	xfconf-query -c xsettings -p /Net/IconThemeName -n -t string -s "Numix-Square"

	CMD=`grep IconThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep IconThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done

	# Set compositor
	xfconf-query -c xfwm4 -p /general/show_frame_shadow -n -t bool -s "true"
	CMD=`grep show_frame_shadow ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep show_frame_shadow ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done

	# Set workspaces count
	xfconf-query -c xfwm4 -p /general/workspace_count -n -t int -s 2
	CMD=`grep workspace_count ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep workspace_count ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done

	# Set panels
	xfconf-query -c xfce4-panel -p /panels/panel-2/autohide -n -t bool -s "true"
	CMD=`grep autohide ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep autohide ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done
	xfconf-query -c xfce4-panel -p /panels/panel-1/size -n -t int -s 25
	CMD=`grep size ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep size ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done

	# Set menu logo
	xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-icon -n -t string -s "/usr/share/antergos/antergos-menu-logo-dark-bg.png"

	terminal-profile 'gnome'
}

mate() {
	gsettings set org.mate.Marco.general theme 'Numix-Frost-Light'
	gsettings set org.mate.Marco.general num-workspaces 1
	gsettings set org.mate.Marco.general compositing-manager true
	gsettings set org.mate.Marco.general side-by-side-tiling true
	gsettings set org.mate.NotificationDaemon theme Coco
	gsettings set org.mate.SettingsDaemon.plugins.datetime active true
	gsettings set org.mate.SettingsDaemon.plugins.datetime priority 99
	gsettings set com.linuxmint.mintmenu.plugins.applications categories-mouse-over true
	gsettings set com.linuxmint.mintmenu.plugins.applications category-hover-delay 150
	gsettings set com.linuxmint.mintmenu.plugins.applications default-tab -1
	gsettings set com.linuxmint.mintmenu.plugins.applications do-not-filter false
	gsettings set com.linuxmint.mintmenu.plugins.applications fav-cols 2
	gsettings set com.linuxmint.mintmenu.plugins.applications favicon-size 48
	gsettings set com.linuxmint.mintmenu.plugins.applications height 410
	gsettings set com.linuxmint.mintmenu.plugins.applications hide-separator false
	gsettings set com.linuxmint.mintmenu.plugins.applications icon 'applications-accessories'
	gsettings set com.linuxmint.mintmenu.plugins.applications icon-size 22
	gsettings set com.linuxmint.mintmenu.plugins.applications last-active-tab 0
	gsettings set com.linuxmint.mintmenu.plugins.applications minimized false
	gsettings set com.linuxmint.mintmenu.plugins.applications remember-filter false
	gsettings set com.linuxmint.mintmenu.plugins.applications search-command 'mate-search-tool --named "%s" --start'
	gsettings set com.linuxmint.mintmenu.plugins.applications show-application-comments true
	gsettings set com.linuxmint.mintmenu.plugins.applications show-category-icons true
	gsettings set com.linuxmint.mintmenu.plugins.applications sticky false
	gsettings set com.linuxmint.mintmenu.plugins.applications swap-generic-name true
	gsettings set com.linuxmint.mintmenu.plugins.applications use-apt false
	gsettings set com.linuxmint.mintmenu.plugins.applications width 480
	gsettings set org.mate.background background-fade true
	gsettings set org.mate.background color-shading-type 'vertical-gradient'
	gsettings set org.mate.background draw-background true
	gsettings set org.mate.background picture-filename '/usr/share/antergos/wallpapers/antergos-wallpaper.png'
	gsettings set org.mate.background picture-opacity 100
	gsettings set org.mate.background picture-options 'zoom'
	gsettings set org.mate.background primary-color '#58589191bcbc'
	gsettings set org.mate.background secondary-color '#3c3c8f8f2525'
	gsettings set org.mate.background show-desktop-icons false
	gsettings set org.mate.SettingsDaemon.plugins.keyboard active true
	gsettings set org.mate.SettingsDaemon.plugins.keyboard priority 6
	gsettings set org.mate.session idle-delay 5
	gsettings set org.mate.session logout-prompt true
	gsettings set org.mate.SettingsDaemon.plugins.background active true
	gsettings set org.mate.SettingsDaemon.plugins.background priority 97
	gsettings set org.mate.applications-browser exec 'chromium'
	gsettings set org.mate.applications-browser needs-term false
	gsettings set org.mate.applications-browser nremote true
	gsettings set org.mate.SettingsDaemon.plugins.xsettings active true
	gsettings set org.mate.SettingsDaemon.plugins.xsettings priority 2
	gsettings set org.mate.peripherals-keyboard numlock-state 'on'
	gsettings set org.mate.peripherals-keyboard remember-numlock-state true
	gsettings set org.mate.peripherals-keyboard repeat true
	gsettings set org.mate.SettingsDaemon.plugins.xrdb active true
	gsettings set org.mate.SettingsDaemon.plugins.xrdb priority 90
	gsettings set org.mate.applications-terminal exec 'mate-terminal'
	gsettings set org.mate.applications-terminal exec-arg '-x'
	gsettings set org.mate.Marco.keybinding-commands command-1 'sudo killall X'
	gsettings set org.mate.Marco.keybinding-commands command-screenshot 'mate-screenshot'
	gsettings set org.mate.Marco.keybinding-commands command-window-screenshot 'mate-screenshot --window'
	gsettings set org.mate.thumbnailers disable-all false
	gsettings set org.mate.search-tool quick-search-excluded-paths "['/mnt/*', '/media/*', '/dev/*', '/tmp/*', '/proc/*', '/var/*']"
	gsettings set org.mate.search-tool quick-search-second-scan-excluded-paths "['/']"
	gsettings set org.mate.search-tool show-additional-options false
	gsettings set com.linuxmint.mintmenu.plugins.recent height 385
	gsettings set com.linuxmint.mintmenu.plugins.recent hide-separator false
	gsettings set com.linuxmint.mintmenu.plugins.recent icon 'mate-fs-directory'
	gsettings set com.linuxmint.mintmenu.plugins.recent minimized false
	gsettings set com.linuxmint.mintmenu.plugins.recent num-recent-docs 10
	gsettings set com.linuxmint.mintmenu.plugins.recent recent-font-size 9
	gsettings set com.linuxmint.mintmenu.plugins.recent sticky false
	gsettings set com.linuxmint.mintmenu.plugins.recent width 250
	gsettings set org.mate.caja.sidebar-panels.tree show-only-directories true
	gsettings set org.mate.panel default-layout 'antergos'
	gsettings set org.mate.panel confirm-panel-remove true
	gsettings set org.mate.panel disable-force-quit false
	gsettings set org.mate.panel drawer-autoclose true
	gsettings set org.mate.panel enable-animations true
	gsettings set org.mate.panel enable-autocompletion true
	gsettings set org.mate.panel enable-program-list true
	gsettings set org.mate.panel highlight-launchers-on-mouseover true
	gsettings set org.mate.panel history-mate-run []
	gsettings set org.mate.panel locked-down false
	gsettings set org.mate.panel object-id-list "['menu', 'show-desktop', 'launcher-1', 'launcher-2', 'launcher-3', 'window-list', 'notification-area', 'clock']"
	gsettings set org.mate.panel show-program-list false
	gsettings set org.mate.panel tooltips-enabled true
	gsettings set org.mate.panel toplevel-id-list "['bottom']"
	gsettings set org.mate.SettingsDaemon.plugins.clipboard active true
	gsettings set org.mate.SettingsDaemon.plugins.clipboard priority 99
	gsettings set org.mate.SettingsDaemon.plugins.keybindings active true
	gsettings set org.mate.SettingsDaemon.plugins.keybindings priority 6
	gsettings set com.linuxmint.mintmenu applet-icon '/usr/share/antergos/antergos-menu-logo-dark-bg'
	gsettings set com.linuxmint.mintmenu applet-icon-size 25
	gsettings set com.linuxmint.mintmenu applet-text 'Menu'
	gsettings set com.linuxmint.mintmenu border-width 1
	gsettings set com.linuxmint.mintmenu custom-border-color '#001155'
	gsettings set com.linuxmint.mintmenu custom-color '#F2F5FF'
	gsettings set com.linuxmint.mintmenu custom-heading-color '#001155'
	gsettings set com.linuxmint.mintmenu hide-applet-icon false
	gsettings set com.linuxmint.mintmenu hot-key 'Super_L'
	gsettings set com.linuxmint.mintmenu offset 0
	gsettings set com.linuxmint.mintmenu opacity 97
	gsettings set com.linuxmint.mintmenu plugins-list "['places', 'system_management', 'newpane', 'applications']"
	gsettings set com.linuxmint.mintmenu start-with-favorites true
	gsettings set com.linuxmint.mintmenu theme-name 'default'
	gsettings set com.linuxmint.mintmenu tooltips-enabled true
	gsettings set com.linuxmint.mintmenu use-custom-color false
	gsettings set com.linuxmint.mintmenu.plugins.system_management allow-scrollbar false
	gsettings set com.linuxmint.mintmenu.plugins.system_management height 160
	gsettings set com.linuxmint.mintmenu.plugins.system_management hide-separator false
	gsettings set com.linuxmint.mintmenu.plugins.system_management icon 'preferences-system'
	gsettings set com.linuxmint.mintmenu.plugins.system_management icon-size 16
	gsettings set com.linuxmint.mintmenu.plugins.system_management minimized false
	gsettings set com.linuxmint.mintmenu.plugins.system_management show-control-center true
	gsettings set com.linuxmint.mintmenu.plugins.system_management show-lock-screen true
	gsettings set com.linuxmint.mintmenu.plugins.system_management show-logout true
	gsettings set com.linuxmint.mintmenu.plugins.system_management show-package-manager false
	gsettings set com.linuxmint.mintmenu.plugins.system_management show-quit true
	gsettings set com.linuxmint.mintmenu.plugins.system_management show-software-manager false
	gsettings set com.linuxmint.mintmenu.plugins.system_management show-terminal true
	gsettings set com.linuxmint.mintmenu.plugins.system_management sticky false
	gsettings set com.linuxmint.mintmenu.plugins.system_management width 200
	gsettings set org.gnome.desktop.interface clock-format '12h'
	gsettings set org.gnome.desktop.interface clock-show-date true
	gsettings set org.gnome.desktop.interface clock-show-seconds false
	gsettings set org.gnome.desktop.interface gtk-theme 'Numix-Frost-Light'
	gsettings set org.gnome.desktop.interface icon-theme 'Numix-Square'
	gsettings set com.linuxmint.mintmenu.plugins.places allow-scrollbar false
	gsettings set com.linuxmint.mintmenu.plugins.places height 180
	gsettings set com.linuxmint.mintmenu.plugins.places hide-separator false
	gsettings set com.linuxmint.mintmenu.plugins.places icon 'mate-fs-directory.png'
	gsettings set com.linuxmint.mintmenu.plugins.places icon-size 16
	gsettings set com.linuxmint.mintmenu.plugins.places minimized false
	gsettings set com.linuxmint.mintmenu.plugins.places show-computer true
	gsettings set com.linuxmint.mintmenu.plugins.places show-desktop true
	gsettings set com.linuxmint.mintmenu.plugins.places show-gtk-bookmarks true
	gsettings set com.linuxmint.mintmenu.plugins.places show-home-folder true
	gsettings set com.linuxmint.mintmenu.plugins.places show-network true
	gsettings set com.linuxmint.mintmenu.plugins.places show-trash true
	gsettings set com.linuxmint.mintmenu.plugins.places sticky false
	gsettings set com.linuxmint.mintmenu.plugins.places width 200
	gsettings set org.mate.font-rendering antialiasing 'rgba'
	gsettings set org.mate.font-rendering dpi 96.0
	gsettings set org.mate.font-rendering hinting 'medium'
	gsettings set org.mate.font-rendering rgba-order 'rgb'
	gsettings set org.mate.peripherals-touchpad disable-while-typing false
	gsettings set org.mate.peripherals-touchpad tap-to-click true
	gsettings set org.mate.peripherals-touchpad touchpad-enabled true
	gsettings set org.mate.interface enable-animations true
	gsettings set org.mate.interface file-chooser-backend 'gtk+'
	gsettings set org.mate.interface font-name 'Sans 10'
	gsettings set org.mate.interface gtk-theme 'Numix-Frost-Light'
	gsettings set org.mate.interface icon-theme 'Numix-Square'

	terminal-profile 'mate'
}


enlightenment() {
	echo "TODO"
	# eet -l e.cfg  # list all keys, usually just "config"
	# eet -d e.cfg config e.src # writes human readable values to file e.src
	# $EDITOR e.src # change whatever you like
	# eet -e e.cfg config e.src 1  # compile human readable values to binary form and use compression
}


"${CN_DESKTOP}" 2>&1
