#!/bin/bash -v

DESKTOP=$1


if [[ ${DESKTOP} == 'gnome' ]];then

	# Change keyboard layout
	dbus-launch gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"

	# Set favorite apps
	dbus-launch gsettings set org.gnome.shell favorite-apps "['nautilus.desktop', 'gnome-terminal.desktop', \"${_BROWSER}.desktop\", 'pidgin.desktop', 'gnome-music.desktop']"

	dbus-launch gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'status-menu-buttons@dev.antergos.com', 'dash-to-dock@micxgx.gmail.com']"
	# Change default wallpaper
	dbus-launch gsettings set org.gnome.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png

	# Set GTK Theme
	dbus-launch gsettings set org.gnome.desktop.interface gtk-theme "Numix Frost Light"
	dbus-launch gsettings set org.gnome.desktop.wm.preferences theme "Numix Frost Light"
	dbus-launch gsettings set org.gnome.shell.extensions.user-theme name "Numix Frost Light"

	# Set icon theme
	dbus-launch gsettings set org.gnome.desktop.interface icon-theme "Numix-Square"
	
	# Disable Terminal Bell
	dbus-launch gsettings set org.gnome.desktop.wm.preferences audible-bell false

	dbus-launch gsettings set org.gnome.desktop.screensaver lock-enabled false
	dbus-launch gsettings set org.gnome.desktop.session idle-delay 0

	# Configure touchpad
	dbus-launch gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
	dbus-launch gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
	dbus-launch gsettings set org.gnome.desktop.peripherals.touchpad scroll-method 'two-finger-scrolling'

fi

if [[ ${DESKTOP} == 'cinnamon' ]];then

	# Change keyboard layout
	dbus-launch gsettings set org.cinnamon.desktop.input-sources sources "[('xkb','us')]"

	# Set gtk theme
	dbus-launch gsettings set org.cinnamon.desktop.interface gtk-theme "Numix Frost Light"
	dbus-launch gsettings set org.cinnamon.desktop.wm.preferences theme "Numix Frost Light"

	# Set menu icon
	dbus-launch gsettings set org.cinnamon menu-icon "/usr/share/antergos/antergos-menu.png"

	# Set favorite apps
	dbus-launch gsettings set org.cinnamon favorite-apps "['nemo.desktop', \"${_BROWSER}.desktop\", 'pamac.desktop', 'gnome-terminal.desktop']"

	# Set overview corner to false
	dbus-launch gsettings set org.cinnamon overview-corner "['false:false:false', 'false:false:false', 'false:false:false', 'false:false:false']"

		# Set panel orientation
	dbus-launch gsettings set org.cinnamon desktop-layout "flipped"

	# Set enabled applets
	dbus-launch gsettings set org.cinnamon enabled-applets "['panel1:left:1:menu@cinnamon.org:0', 'panel1:left:2:panel-launchers@cinnamon.org:1', 'panel1:left:3:window-list@cinnamon.org:2', 'panel1:right:0:removable-drives@cinnamon.org:3', 'panel1:right:1:keyboard@cinnamon.org:4', 'panel1:right:2:bluetooth@cinnamon.org:5', 'panel1:right:4:systray@cinnamon.org:7', 'panel1:right:5:power@cinnamon.org:8', 'panel1:right:6:network@cinnamon.org:6', 'panel1:right:7:sound@cinnamon.org:9', 'panel1:right:8:calendar@cinnamon.org:10', 'panel1:right:9:settings@cinnamon.org:11']"

	# Disable keyboard flags
	dbus-launch gsettings set org.cinnamon keyboard-applet-use-flags "false"
	
	# Set background
	dbus-launch gsettings set org.cinnamon.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png
	dbus-launch gsettings set org.gnome.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png

	# Set theme
	dbus-launch gsettings set org.cinnamon.theme name "Numix Frost"

	# Set icon theme
	dbus-launch gsettings set org.cinnamon.desktop.interface icon-theme "Numix-Square"
	dbus-launch gsettings set org.gnome.desktop.interface icon-theme "Numix-Square"

	# Disable Terminal Bell
	dbus-launch gsettings set org.cinnamon.desktop.wm.preferences audible-bell false
	dbus-launch gsettings set org.gnome.desktop.wm.preferences audible-bell false

	# Configure touchpad
	dbus-launch gsettings set org.cinnamon.settings-daemon.peripherals.touchpad tap-to-click true
	dbus-launch gsettings set org.cinnamon.settings-daemon.peripherals.touchpad touchpad-enabled true
	dbus-launch gsettings set org.cinnamon.settings-daemon.peripherals.touchpad scroll-method 'two-finger-scrolling'
	
fi

if [[ ${DESKTOP} == 'xfce' ]];then

	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml


	# Set background
	dbus-launch xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path -n -t string -s "/usr/share/antergos/wallpapers/antergos-wallpaper.png"
	CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
	    sleep 3
		CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done

	# Set theme
	CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
	    sleep 3
		CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done
	dbus-launch xfconf-query -c xsettings -p /Net/ThemeName -n -t string -s "Numix Frost"

	CMD=`grep ThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
        sleep 3
		CMD=`grep ThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done
	dbus-launch xfconf-query -c xfwm4 -p /general/theme -n -t string -s "Numix Frost Light"

	# Set icon theme
	CMD=`grep theme ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
        sleep 3
		CMD=`grep theme ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	dbus-launch xfconf-query -c xsettings -p /Net/IconThemeName -n -t string -s "Numix-Square"

	# Set compositor
	CMD=`grep IconThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
        sleep 3
		CMD=`grep IconThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done
	dbus-launch xfconf-query -c xfwm4 -p /general/show_frame_shadow -n -t bool -s "true"

	# Set workspaces count
	CMD=`grep show_frame_shadow ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
        sleep 3
		CMD=`grep show_frame_shadow ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	dbus-launch xfconf-query -c xfwm4 -p /general/workspace_count -n -t int -s 2

	# Set panels
	CMD=`grep workspace_count ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
        sleep 3
		CMD=`grep workspace_count ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	dbus-launch xfconf-query -c xfce4-panel -p /panels/panel-2/autohide -n -t bool -s "true"

	CMD=`grep autohide ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
        sleep 3
		CMD=`grep autohide ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done
	dbus-launch xfconf-query -c xfce4-panel -p /panels/panel-1/size -n -t int -s 25

	# Set menu logo
	CMD=`grep size ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
        sleep 3
		CMD=`grep size ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done
	dbus-launch xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-icon -n -t string -s "/usr/share/antergos/antergos-menu.png"
fi

if [[ ${DESKTOP} == 'mate' ]]; then


	dbus-launch gsettings set org.mate.Marco.general theme 'Numix Frost Light'
	dbus-launch gsettings set org.mate.Marco.general visual-bell false
	dbus-launch gsettings set org.mate.Marco.general num-workspaces 2
	dbus-launch gsettings set org.mate.Marco.general compositing-manager true
	dbus-launch gsettings set org.mate.Marco.general side-by-side-tiling true
	dbus-launch gsettings set org.mate.NotificationDaemon theme Slider
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.datetime active true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.datetime priority 99
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications categories-mouse-over true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications category-hover-delay 150
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications default-tab -1
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications do-not-filter false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications fav-cols 2
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications favicon-size 48
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications height 410
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications hide-separator false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications icon 'applications-accessories'
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications icon-size 22
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications last-active-tab 0
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications minimized false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications remember-filter false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications search-command 'mate-search-tool --named "%s" --start'
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications show-application-comments true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications show-category-icons true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications sticky false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications swap-generic-name true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications use-apt false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.applications width 480
	dbus-launch gsettings set org.mate.background background-fade true
	dbus-launch gsettings set org.mate.background color-shading-type 'vertical-gradient'
	dbus-launch gsettings set org.mate.background draw-background true
	dbus-launch gsettings set org.mate.background picture-filename '/usr/share/antergos/wallpapers/antergos-wallpaper.png'
	dbus-launch gsettings set org.mate.background picture-opacity 100
	dbus-launch gsettings set org.mate.background picture-options 'zoom'
	dbus-launch gsettings set org.mate.background primary-color '#58589191bcbc'
	dbus-launch gsettings set org.mate.background secondary-color '#3c3c8f8f2525'
	dbus-launch gsettings set org.mate.background show-desktop-icons false
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.keyboard active true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.keyboard priority 6
	dbus-launch gsettings set org.mate.session idle-delay 5
	dbus-launch gsettings set org.mate.session logout-prompt true
	dbus-launch gsettings set org.gnome.desktop.screensaver idle-activation-enabled true
	dbus-launch gsettings set org.gnome.desktop.screensaver lock-delay 0
	dbus-launch gsettings set org.gnome.desktop.screensaver lock-enabled true
	dbus-launch gsettings set org.gnome.desktop.screensaver picture-uri 'file://usr/share/antergos/wallpapers/antergos-wallpaper.png'
	dbus-launch gsettings set org.gnome.desktop.screensaver primary-color '#023c88'
	dbus-launch gsettings set org.gnome.desktop.screensaver secondary-color '#5789ca'
	dbus-launch gsettings set org.gnome.desktop.screensaver show-full-name-in-top-bar true
	dbus-launch gsettings set org.gnome.desktop.screensaver status-message-enabled true
	dbus-launch gsettings set org.gnome.desktop.screensaver user-switch-enabled true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.background active true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.background priority 97
	dbus-launch gsettings set org.mate.applications-browser exec 'chromium'
	dbus-launch gsettings set org.mate.applications-browser needs-term false
	dbus-launch gsettings set org.mate.applications-browser nremote true
	dbus-launch gsettings set org.gnome.desktop.background color-shading-type 'solid'
	dbus-launch gsettings set org.gnome.desktop.background picture-opacity 100
	dbus-launch gsettings set org.gnome.desktop.background picture-options 'zoom'
	dbus-launch gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/antergos/wallpapers/antergos-wallpaper.png'
	dbus-launch gsettings set org.gnome.desktop.background primary-color '#023c88'
	dbus-launch gsettings set org.gnome.desktop.background secondary-color '#5789ca'
	dbus-launch gsettings set org.gnome.desktop.background show-desktop-icons false
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.xsettings active true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.xsettings priority 2
	dbus-launch gsettings set org.mate.peripherals-keyboard bell-custom-file ''
	dbus-launch gsettings set org.mate.peripherals-keyboard bell-duration 100
	dbus-launch gsettings set org.mate.peripherals-keyboard bell-mode 'off'
	dbus-launch gsettings set org.mate.peripherals-keyboard bell-pitch 400
	dbus-launch gsettings set org.mate.peripherals-keyboard click true
	dbus-launch gsettings set org.mate.peripherals-keyboard click-volume 0
	dbus-launch gsettings set org.mate.peripherals-keyboard delay 500
	dbus-launch gsettings set org.mate.peripherals-keyboard numlock-state 'on'
	dbus-launch gsettings set org.mate.peripherals-keyboard rate 30
	dbus-launch gsettings set org.mate.peripherals-keyboard remember-numlock-state true
	dbus-launch gsettings set org.mate.peripherals-keyboard repeat true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.xrdb active true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.xrdb priority 90
	dbus-launch gsettings set org.mate.applications-terminal exec 'mate-terminal'
	dbus-launch gsettings set org.mate.applications-terminal exec-arg '-x'
	dbus-launch gsettings set org.mate.Marco.keybinding-commands command-1 'sudo killall X'
	dbus-launch gsettings set org.mate.Marco.keybinding-commands command-screenshot 'mate-screenshot'
	dbus-launch gsettings set org.mate.Marco.keybinding-commands command-window-screenshot 'mate-screenshot --window'
	dbus-launch gsettings set org.mate.thumbnailers disable-all false
	dbus-launch gsettings set org.mate.search-tool quick-search-excluded-paths ['/mnt/*', '/media/*', '/dev/*', '/tmp/*', '/proc/*', '/var/*']
	dbus-launch gsettings set org.mate.search-tool quick-search-second-scan-excluded-paths ['/']
	dbus-launch gsettings set org.mate.search-tool show-additional-options false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent height 385
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent hide-separator false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent icon 'mate-fs-directory'
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent minimized false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent num-recent-docs 10
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent recent-font-size 9
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent sticky false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.recent width 250
	dbus-launch gsettings set org.mate.caja.sidebar-panels.tree show-only-directories true
	dbus-launch gsettings set org.gnome.system.dns_sd display-local 'merged'
	dbus-launch gsettings set org.gnome.system.dns_sd extra-domains ''
	dbus-launch gsettings set org.mate.panel default-layout 'antergos'
	dbus-launch gsettings set org.mate.panel confirm-panel-remove true
	dbus-launch gsettings set org.mate.panel disable-force-quit false
	dbus-launch gsettings set org.mate.panel disable-log-out false
	dbus-launch gsettings set org.mate.panel disabled-applets @as []
	dbus-launch gsettings set org.mate.panel drawer-autoclose true
	dbus-launch gsettings set org.mate.panel enable-animations true
	dbus-launch gsettings set org.mate.panel enable-autocompletion true
	dbus-launch gsettings set org.mate.panel enable-program-list true
	dbus-launch gsettings set org.mate.panel highlight-launchers-on-mouseover true
	dbus-launch gsettings set org.mate.panel history-mate-run []
	dbus-launch gsettings set org.mate.panel locked-down false
	dbus-launch gsettings set org.mate.panel object-id-list ['notification-area', 'clock', 'show-desktop', 'window-list', 'workspace-switcher', 'menu-bar']
	dbus-launch gsettings set org.mate.panel show-program-list false
	dbus-launch gsettings set org.mate.panel tooltips-enabled true
	dbus-launch gsettings set org.mate.panel toplevel-id-list ['top', 'bottom']
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.clipboard active true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.clipboard priority 99
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.keybindings active true
	dbus-launch gsettings set org.mate.SettingsDaemon.plugins.keybindings priority 6
	dbus-launch gsettings set com.linuxmint.mintmenu applet-icon '/usr/share/antergos/antergos-menu.png'
	dbus-launch gsettings set com.linuxmint.mintmenu applet-icon-size 25
	dbus-launch gsettings set com.linuxmint.mintmenu applet-text 'Menu'
	dbus-launch gsettings set com.linuxmint.mintmenu border-width 1
	dbus-launch gsettings set com.linuxmint.mintmenu custom-border-color '#001155'
	dbus-launch gsettings set com.linuxmint.mintmenu custom-color '#F2F5FF'
	dbus-launch gsettings set com.linuxmint.mintmenu custom-heading-color '#001155'
	dbus-launch gsettings set com.linuxmint.mintmenu hide-applet-icon false
	dbus-launch gsettings set com.linuxmint.mintmenu hot-key 'Super_L'
	dbus-launch gsettings set com.linuxmint.mintmenu offset 0
	dbus-launch gsettings set com.linuxmint.mintmenu opacity 97
	dbus-launch gsettings set com.linuxmint.mintmenu plugins-list ['places', 'system_management', 'newpane', 'applications']
	dbus-launch gsettings set com.linuxmint.mintmenu start-with-favorites true
	dbus-launch gsettings set com.linuxmint.mintmenu theme-name 'default'
	dbus-launch gsettings set com.linuxmint.mintmenu tooltips-enabled true
	dbus-launch gsettings set com.linuxmint.mintmenu use-custom-color false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management allow-scrollbar false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management height 160
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management hide-separator false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management icon 'preferences-system'
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management icon-size 16
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management minimized false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management show-control-center true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management show-lock-screen true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management show-logout true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management show-package-manager false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management show-quit true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management show-software-manager false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management show-terminal true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management sticky false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.system_management width 200
	dbus-launch gsettings set org.gnome.desktop.interface clock-format '12h'
	dbus-launch gsettings set org.gnome.desktop.interface clock-show-date true
	dbus-launch gsettings set org.gnome.desktop.interface clock-show-seconds false
	dbus-launch gsettings set org.gnome.desktop.interface gtk-theme 'Numix Frost'
	dbus-launch gsettings set org.gnome.desktop.interface icon-theme 'Numix-Square'
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places allow-scrollbar false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places custom-names @as []
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places custom-paths @as []
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places height 180
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places hide-separator false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places icon 'mate-fs-directory.png'
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places icon-size 16
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places minimized false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places show-computer true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places show-desktop true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places show-gtk-bookmarks true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places show-home-folder true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places show-network true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places show-trash true
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places sticky false
	dbus-launch gsettings set com.linuxmint.mintmenu.plugins.places width 200
	dbus-launch gsettings set org.mate.font-rendering antialiasing 'rgba'
	dbus-launch gsettings set org.mate.font-rendering dpi 92.0
	dbus-launch gsettings set org.mate.font-rendering hinting 'medium'
	dbus-launch gsettings set org.mate.font-rendering rgba-order 'rgb'
	dbus-launch gsettings set org.mate.peripherals-touchpad disable-while-typing false
	dbus-launch gsettings set org.mate.peripherals-touchpad horiz-scroll-enabled false
	dbus-launch gsettings set org.mate.peripherals-touchpad scroll-method 2
	dbus-launch gsettings set org.mate.peripherals-touchpad tap-to-click true
	dbus-launch gsettings set org.mate.peripherals-touchpad touchpad-enabled true
	dbus-launch gsettings set org.mate.interface enable-animations true
	dbus-launch gsettings set org.mate.interface file-chooser-backend 'gtk+'
	dbus-launch gsettings set org.mate.interface font-name 'Sans 10'
	dbus-launch gsettings set org.mate.interface gtk-color-scheme ''
	dbus-launch gsettings set org.mate.interface gtk-theme 'Numix Frost'
	dbus-launch gsettings set org.mate.interface icon-theme 'Numix-Square'

fi

